# -*- coding: utf-8 -*-
"""stftrnn2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BrlvUdV_0T6FHQmSvX3c-5JFJs-G7CZr

MODEL LOADING
"""

# =========================================================
# BAGIAN 1: PERSIAPAN LINGKUNGAN DAN PEMUATAN MODEL
# (Dijalankan satu kali)
# =========================================================
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import librosa
import soundfile as sf
import matplotlib.pyplot as plt
from google.colab import drive
import IPython.display as ipd
from google.colab import files

# ---------------------------------------------------------
# 1. Menghubungkan Google Drive
# ---------------------------------------------------------
drive.mount('/content/drive')

# ---------------------------------------------------------
# 2. Definisi Arsitektur Model dengan Panjang Waktu Fleksibel
# ---------------------------------------------------------
def build_flexible_model():
    inputs = layers.Input(shape=(None, 257))  # Dimensi waktu bersifat fleksibel
    x = layers.LSTM(256, return_sequences=True)(inputs)
    x = layers.Dropout(0.2)(x)
    x = layers.LSTM(256, return_sequences=True)(x)
    x = layers.Dropout(0.2)(x)
    outputs = layers.TimeDistributed(
        layers.Dense(257, activation='relu')
    )(x)
    model = models.Model(inputs=inputs, outputs=outputs)
    return model

# ---------------------------------------------------------
# 3. Memuat Model dan Bobot Terlatih
# ---------------------------------------------------------
print("Memuat model denoising berbasis LSTM.")
flexible_model = build_flexible_model()

# Path menuju file model terlatih (.h5) pada Google Drive
model_path = '/content/drive/MyDrive/datasetrnn1/MODEL_JADI_LSTM.h5'

if os.path.exists(model_path):
    flexible_model.load_weights(model_path)
    print("Model berhasil dimuat dan siap digunakan.")
else:
    print("Kesalahan: File model tidak ditemukan pada path yang ditentukan.")
    print("Periksa kembali lokasi file .h5 pada Google Drive.")

# ---------------------------------------------------------
# 4. Fungsi Denoising Audio (Inference)
# ---------------------------------------------------------
def denoise_audio(audio_path):
    # Memuat sinyal audio dan melakukan resampling ke 16 kHz
    y, sr = librosa.load(audio_path, sr=16000)

    # Transformasi Short-Time Fourier Transform (STFT)
    S = librosa.stft(y, n_fft=512, hop_length=256)
    S_mag = np.abs(S).T
    S_phase = np.angle(S)

    # Prediksi magnitude spectrogram menggunakan model
    X_input = np.expand_dims(S_mag, axis=0)
    pred_mag = flexible_model.predict(X_input, verbose=0)[0].T

    # Rekonstruksi sinyal audio menggunakan inverse STFT
    y_clean = librosa.istft(
        pred_mag * np.exp(1j * S_phase),
        hop_length=256
    )

    return y, y_clean, sr

"""TEST SET EXTRACTION"""

import zipfile
import shutil

# =========================================================
# KONFIGURASI EKSTRAK DATA UJI
# =========================================================
drive_folder = '/content/drive/MyDrive/datasetrnn1'  # Direktori dataset pada Google Drive
local_extract_path = '/content/data_raw'
target_zips = [
    'clean_testset_wav.zip',
    'noisy_testset_wav.zip'
]

print("Memulai proses ekstraksi dataset uji dari Google Drive.")

for zip_name in target_zips:
    source = os.path.join(drive_folder, zip_name)
    dest = os.path.join('/content', zip_name)

    # Validasi keberadaan file ZIP pada Google Drive
    if os.path.exists(source):
        shutil.copy(source, dest)
        with zipfile.ZipFile(dest, 'r') as zip_ref:
            zip_ref.extractall(local_extract_path)
        os.remove(dest)
        print(f"File berhasil diekstrak: {zip_name}")
    else:
        print(f"Kesalahan: File {zip_name} tidak ditemukan pada Google Drive.")

print("Proses ekstraksi data uji telah selesai. Dataset siap digunakan.")

"""MODEL EVALUATION"""

import os
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt
import IPython.display as ipd
from tqdm.notebook import tqdm

# =========================================================
# 1. INISIALISASI DAN PENCARIAN DIREKTORI DATA UJI
# =========================================================
local_extract_path = '/content/data_raw'
test_clean_path = None
test_noisy_path = None

for root, dirs, files in os.walk(local_extract_path):
    for d in dirs:
        if 'clean_testset' in d:
            test_clean_path = os.path.join(root, d)
        elif 'noisy_testset' in d:
            test_noisy_path = os.path.join(root, d)

# ---------------------------------------------------------
# Fungsi Perhitungan Signal-to-Noise Ratio (SNR)
# ---------------------------------------------------------
def calculate_snr(clean, reconstructed):
    min_len = min(len(clean), len(reconstructed))
    clean = clean[:min_len]
    reconstructed = reconstructed[:min_len]
    noise_residual = clean - reconstructed
    power_clean = np.sum(clean ** 2)
    power_noise = np.sum(noise_residual ** 2)
    if power_noise == 0:
        return 100
    return 10 * np.log10(power_clean / power_noise)

# =========================================================
# 2. PEMROSESAN 100 FILE AUDIO DATA UJI
# =========================================================
if test_clean_path and test_noisy_path:

    # Seluruh file diurutkan secara alfabet untuk menjaga konsistensi
    all_files = sorted(
        [f for f in os.listdir(test_noisy_path) if f.endswith('.wav')]
    )

    # Mengambil 100 file pertama hasil pengurutan
    test_files = all_files[:100]

    snr_in, snr_out = [], []
    demo_data = {}

    print(f"Memproses {len(test_files)} file audio secara berurutan.")

    for i, f in enumerate(tqdm(test_files)):
        try:
            # Memuat audio noisy dan clean
            y_noisy, sr = librosa.load(
                os.path.join(test_noisy_path, f),
                sr=16000
            )
            y_clean, _ = librosa.load(
                os.path.join(test_clean_path, f),
                sr=16000
            )

            # Transformasi STFT
            S = librosa.stft(y_noisy, n_fft=512, hop_length=256)

            # Inferensi menggunakan model
            pred_mag = flexible_model.predict(
                np.expand_dims(np.abs(S).T, 0),
                verbose=0
            )[0].T

            y_denoised = librosa.istft(
                pred_mag * np.exp(1j * np.angle(S)),
                hop_length=256
            )

            # Perhitungan SNR sebelum dan sesudah denoising
            s_in = calculate_snr(y_clean, y_noisy)
            s_out = calculate_snr(y_clean, y_denoised)

            snr_in.append(s_in)
            snr_out.append(s_out)

            # Menyimpan contoh file pertama untuk keperluan demonstrasi
            if i == 0:
                demo_data = {
                    'name': f,
                    'y_noisy': y_noisy,
                    'y_clean': y_clean,
                    'y_denoised': y_denoised,
                    'sr': sr,
                    'gain': s_out - s_in
                }
        except:
            continue

    avg_gain = np.mean(snr_out) - np.mean(snr_in)

    # =====================================================
    # 3. OUTPUT VISUALISASI: SCATTER PLOT SNR
    # =====================================================
    plt.figure(figsize=(15, 6))

    plt.subplot(1, 2, 1)
    plt.plot([-5, 25], [-5, 25], 'k--', alpha=0.5)
    colors = ['green' if o > i else 'red' for i, o in zip(snr_in, snr_out)]
    plt.scatter(
        snr_in,
        snr_out,
        c=colors,
        s=50,
        alpha=0.7,
        edgecolors='k'
    )
    plt.title(f'Statistik 100 File Audio (Gain Rata-rata: +{avg_gain:.2f} dB)')
    plt.xlabel('SNR Masukan (dB)')
    plt.ylabel('SNR Keluaran (dB)')
    plt.grid(True, alpha=0.3)

    # =====================================================
    # 4. OUTPUT VISUALISASI: SPEKTROGRAM
    # =====================================================
    # Spektrogram sinyal noisy
    plt.subplot(2, 2, 2)
    librosa.display.specshow(
        librosa.amplitude_to_db(
            np.abs(librosa.stft(demo_data['y_noisy'])),
            ref=np.max
        ),
        y_axis='log',
        x_axis='time',
        sr=16000,
        cmap='magma'
    )
    plt.title(f"Sebelum Denoising: {demo_data['name']}")
    plt.colorbar(format='%+2.0f dB')

    # Spektrogram sinyal hasil denoising
    plt.subplot(2, 2, 4)
    librosa.display.specshow(
        librosa.amplitude_to_db(
            np.abs(librosa.stft(demo_data['y_denoised'])),
            ref=np.max
        ),
        y_axis='log',
        x_axis='time',
        sr=16000,
        cmap='magma'
    )
    plt.title("Sesudah Denoising (Hasil Model)")
    plt.colorbar(format='%+2.0f dB')

    plt.tight_layout()
    plt.show()

    # =====================================================
    # 5. OUTPUT AUDIO: PEMUTAR AUDIO DEMONSTRASI
    # =====================================================
    print("\n" + "=" * 50)
    print(f"Demonstrasi Audio: {demo_data['name']}")
    print("=" * 50)

    print("1. Sinyal masukan (Noisy):")
    ipd.display(
        ipd.Audio(demo_data['y_noisy'], rate=demo_data['sr'])
    )

    print("\n2. Sinyal keluaran (Hasil Denoising):")
    ipd.display(
        ipd.Audio(demo_data['y_denoised'], rate=demo_data['sr'])
    )

    print("\n3. Sinyal referensi (Clean):")
    ipd.display(
        ipd.Audio(demo_data['y_clean'], rate=demo_data['sr'])
    )

else:
    print(
        "Data uji tidak ditemukan. "
        "Pastikan proses ekstraksi dataset telah dijalankan."
    )

"""REAL-TIME DEMO (GRADIO)"""

import gradio as gr
import librosa
import numpy as np
import matplotlib.pyplot as plt

# =========================================================
# 1. FUNGSI PEMROSESAN AUDIO (BACKEND)
# =========================================================
def process_audio_live(audio_filepath):
    if audio_filepath is None:
        return None, None, None

    # A. Memuat audio dan melakukan resampling ke 16 kHz
    # Gradio menyediakan path sementara untuk berkas audio
    y_noisy, sr = librosa.load(audio_filepath, sr=16000)

    # B. Proses inferensi menggunakan model
    S = librosa.stft(y_noisy, n_fft=512, hop_length=256)
    S_mag = np.abs(S).T
    S_phase = np.angle(S)

    X_input = np.expand_dims(S_mag, axis=0)
    pred_mag = flexible_model.predict(X_input, verbose=0)[0].T

    # Rekonstruksi sinyal audio hasil denoising
    y_clean = librosa.istft(
        pred_mag * np.exp(1j * S_phase),
        hop_length=256
    )

    # C. Visualisasi spektrogram
    fig = plt.figure(figsize=(10, 6))

    # Spektrogram sinyal masukan (noisy)
    plt.subplot(2, 1, 1)
    librosa.display.specshow(
        librosa.amplitude_to_db(
            np.abs(librosa.stft(y_noisy)),
            ref=np.max
        ),
        y_axis='log',
        x_axis='time',
        sr=16000,
        cmap='magma'
    )
    plt.title("Sinyal Masukan (Noisy)")
    plt.colorbar(format='%+2.0f dB')

    # Spektrogram sinyal keluaran (hasil denoising)
    plt.subplot(2, 1, 2)
    librosa.display.specshow(
        librosa.amplitude_to_db(
            np.abs(librosa.stft(y_clean)),
            ref=np.max
        ),
        y_axis='log',
        x_axis='time',
        sr=16000,
        cmap='magma'
    )
    plt.title("Sinyal Keluaran (Hasil Denoising)")
    plt.colorbar(format='%+2.0f dB')
    plt.tight_layout()

    # Mengembalikan audio masukan, audio keluaran, dan visualisasi
    return (16000, y_noisy), (16000, y_clean), fig

# =========================================================
# 2. PERANCANGAN ANTARMUKA PENGGUNA (FRONT-END)
# =========================================================
interface = gr.Interface(
    fn=process_audio_live,
    inputs=gr.Audio(
        sources=["microphone", "upload"],
        type="filepath",
        label="Rekam Audio atau Unggah Berkas"
    ),
    outputs=[
        gr.Audio(label="Audio Masukan (Noisy)"),
        gr.Audio(label="Audio Keluaran (Hasil Denoising)"),
        gr.Plot(label="Visualisasi Spektrogram")
    ],
    title="Demo Speech Enhancement Real-Time",
    description=(
        "Aplikasi ini memungkinkan pengguna merekam atau mengunggah audio "
        "untuk mendemonstrasikan kemampuan model dalam mereduksi noise latar."
    ),
    theme="default"
)

# =========================================================
# 3. PELUNCURAN APLIKASI
# =========================================================
print("Menyiapkan dan meluncurkan aplikasi demo.")
interface.launch(share=True, debug=True)

"""DEMO (FILE UPLOAD)"""

import os
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt
import IPython.display as ipd
from google.colab import files

print("Silakan unggah berkas audio yang akan diproses.")
print("Disarankan menggunakan rekaman dengan gangguan kebisingan agar perbedaan hasil dapat diamati.")

# 1. UNGGAH BERKAS AUDIO
uploaded = files.upload()

# 2. PROSES SELURUH BERKAS YANG DIUNGGAH
for f_name in uploaded.keys():
    print(f"\nMemproses berkas: {f_name} ...")

    try:
        # A. Pemrosesan awal audio (resampling ke 16 kHz agar sesuai dengan model)
        y_noisy, sr = librosa.load(f_name, sr=16000)

        # B. Proses inferensi model
        # Short-Time Fourier Transform (STFT)
        S = librosa.stft(y_noisy, n_fft=512, hop_length=256)
        S_mag = np.abs(S).T
        S_phase = np.angle(S)

        # Prediksi magnitudo spektrum menggunakan model
        X_input = np.expand_dims(S_mag, axis=0)
        pred_mag = flexible_model.predict(X_input, verbose=0)[0].T

        # Rekonstruksi sinyal audio menggunakan ISTFT
        y_denoised = librosa.istft(
            pred_mag * np.exp(1j * S_phase),
            hop_length=256
        )

        # C. Visualisasi spektrogram
        plt.figure(figsize=(10, 8))

        # Spektrogram audio masukan
        plt.subplot(2, 1, 1)
        librosa.display.specshow(
            librosa.amplitude_to_db(np.abs(librosa.stft(y_noisy)), ref=np.max),
            y_axis='log',
            x_axis='time',
            sr=16000,
            cmap='magma'
        )
        plt.title(f"Sinyal Audio Masukan (Noisy): {f_name}")
        plt.colorbar(format='%+2.0f dB')

        # Spektrogram audio keluaran
        plt.subplot(2, 1, 2)
        librosa.display.specshow(
            librosa.amplitude_to_db(np.abs(librosa.stft(y_denoised)), ref=np.max),
            y_axis='log',
            x_axis='time',
            sr=16000,
            cmap='magma'
        )
        plt.title("Sinyal Audio Keluaran Setelah Proses Denoising")
        plt.colorbar(format='%+2.0f dB')

        plt.tight_layout()
        plt.show()

        # D. Pemutaran audio
        print("=" * 40)
        print("Perbandingan hasil pemrosesan audio")
        print("=" * 40)

        print(f"1. Audio masukan ({f_name}):")
        ipd.display(ipd.Audio(y_noisy, rate=sr))

        print("\n2. Audio keluaran (hasil denoising):")
        ipd.display(ipd.Audio(y_denoised, rate=sr))
        print("-" * 40)

    except Exception as e:
        print(f"Gagal memproses berkas: {f_name}.")
        print("Pastikan berkas audio valid dan didukung (misalnya .wav atau .mp3).")
        print(f"Detail kesalahan: {e}")

"""OBJECTIVE EVALUATION (SNR)"""

import numpy as np

# 1. Menghitung nilai rata-rata SNR
rata_input = np.mean(snr_in)     # Rata-rata SNR sebelum pemrosesan model
rata_output = np.mean(snr_out)   # Rata-rata SNR setelah pemrosesan model
kenaikan = rata_output - rata_input  # Selisih (gain) SNR

# 2. Menampilkan hasil perhitungan
print("=== NILAI RATA-RATA SNR ===")
print(f"1. SNR Masukan (Input)  : {rata_input:.2f} dB")
print(f"2. SNR Keluaran (Output): {rata_output:.2f} dB")
print(f"3. Peningkatan (Gain)   : +{kenaikan:.2f} dB")